version: '3.8'
services:
  cloud-weather-postgres:
    image: debezium/postgres:15-alpine
    container_name: cloud-weather-postgres
    restart: always
    environment:
      POSTGRES_USER: cloud_weather_dev
      POSTGRES_PASSWORD: cloud_weather_dev
      POSTGRES_DB: cloud_weather_dev
    volumes:
      - postgres-data:/data/db
    ports:
      - 5432:5432
volumes:
  postgres-data:
networks:
  cloud-weather-services:
    driver: bridge
